name: TestActions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libvips-dev
          sudo GOBIN=/tmp go install github.com/xuxinx/go-sumtype@install

      - name: Check exhaustiveness of sum types
        run: /tmp/go-sumtype $(go list ./... | grep -v vendor)

      - name: say hello
        run: echo "Hello, World!"

